#ifndef __org_atosorigin_ctoo_ctoo3_idl__
#define __org_atosorigin_ctoo_ctoo3_idl__

#include <com/sun/star/uno/XInterface.idl>
#include "org/atosorigin/ctOO/XCtOO3.idl"
module org { module atosorigin { module ctOO { 	

	service CtOO3 : org::atosorigin::ctOO::XCtOO3 {

	};
	singleton theCTOO3 : org::atosorigin::ctOO::XCtOO3;
 }; }; };
#endif
