#ifndef __org_atosorigin_ctoo_xctoo3_idl__
#define __org_atosorigin_ctoo_xctoo3_idl__

#include "org/atosorigin/ctOO/Result.idl"

module org { module atosorigin { module ctOO { 	

	interface XCtOO3 {
		sequence<org::atosorigin::ctOO::Result> search([in] string sentence);
		[attribute,readonly] long maxwords;
		[attribute,readonly] sequence<string> domaines;
	};

 }; }; };
#endif
